apiVersion: v1
kind: Service
metadata:
  name: atpalex-web-service
  namespace: prod
spec:
  type: NodePort
  selector:
    app: atpalex-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: atpalex-web
