apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: atpalex-web-hpa
  namespace: prod
spec:
  minReplicas: 1
  maxReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: atpalex-web-deployment
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 95
  behavior:
    scaleDown:
      policies:
        - type: Pods
          value: 4
          periodSeconds: 60
        - type: Percent
          value: 10
          periodSeconds: 60
      selectPolicy: Min
      stabilizationWindowSeconds: 300
    scaleUp:
      policies:
        - type: Pods
          value: 5
          periodSeconds: 70
        - type: Percent
          value: 12
          periodSeconds: 80
      selectPolicy: Max
      stabilizationWindowSeconds: 15
